[package]
name = "irvine-connect-schedule-gtfs"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
geo = "0.26"
chrono = "0.4"
itertools = "0.10"

